apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    group: db
data:
  config.yml: |
    app:
      port: 8080
    postgres:
      user: ""
      password: ""
      host: localhost
      port: 5432
      db: ""
      log_level: 4
